name: pytorch_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - scikit-learn
  - seaborn
  - python-graphviz
  - shap
